name: Setup Cairo Native Dependencies
description: Sets up LLVM and GMP libraries

outputs:
  cairo-native-runtime-library:
    description: The path to the cairo native runtime library
    value: ${{ steps.set-env-vars.outputs.cairo-native-runtime-library }}

runs:
  using: composite
  steps:
    - name: Cache LLVM and Dependencies
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          /usr/lib/llvm-19
          /usr/include/llvm-19
          /var/cache/apt
          /var/lib/apt/lists
        key:
          ${{ runner.os }}-llvm-19-${{ hashFiles('scripts/dependencies.sh') }}

    - name: Install Cairo Native Runtime Dependencies
      if: steps.cache-llvm.outputs.cache-hit != 'true'
      id: set-runtime-deps
      shell: bash
      run: |
        sudo ./scripts/dependencies.sh
