name: Install Rust
description: Install Rust toolchain with caching

runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.82.0
        override: true
        components: clippy
    - uses: Swatinem/rust-cache@v2
