---
name: Workflow - CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  trunk:
    name: Trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap
      - uses: ./.github/workflows/trunk-check.yml

  tests:
    name: Rust tests
    uses: ./.github/workflows/test.yml
