name: Kakarot compilation caching

on:
  workflow_call: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-submodules
  cancel-in-progress: true

jobs:
  submodules:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: pull kakarot submodule and setup
        run: make setup-kakarot
      - name: Save compiled kakarot contracts
        id: cached-contracts
        uses: actions/cache/save@v3
        with:
          path: ./lib/kakarot/build
          key: ${{ runner.os }}-contracts
